/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Multi-Tenant Shop API
 * OpenAPI spec version: 1.0.0
 */

export interface Client {
  id?: string;
  name?: string;
  logoUrl?: string;
}
